name: Build and deploy package to npm and docs to Github pages

on:
  push:
    branches: 
    - main
    - release/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
#   publish_npm:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: 16
#             cache: 'yarn'
#       - run: yarn install
#       - run: yarn test
#       - uses: JS-DevTools/npm-publish@v1
#         with:
#           token: ${{ secrets.NPM_TOKEN }}
  deploy_pages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
#         cache: 'yarn'
    - run: yarn install
    - run: yarn docs

    - name: Deploy docs 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs # The folder the action should deploy.
